### ISSUE TITLE
Drone trigger should use the initiating user

### ISSUE THREAD

**Issue by markwimpory** [UKHomeOffice/drone-trigger#10]
When you use drone trigger to promote between environments it has the username of the person who initiated the original build and NOT the user initiating the promote.

**Comment by vaijab** [comment]
drone-trigger does not really set any users. It just talks to drone API to restart an existing build. It's the existing build that contains the original author of the build and that's what you're seeing. There is nothing we can do from drone-trigger perspective.

I will see what we can do in drone API and more importantly the UI.

**Comment by johnplacek** [comment]
hi @vaijab any luck with the UI? Thanks

**Comment by vaijab** [comment]
@johnplacek hey, was just looking at drone code, we'd have to modify the backend to set the right user first before we can surface that in the UI. I can certainly add that functionality, but I cannot promise when, priorities first.. How urgent/important is this?

**Comment by johnplacek** [comment]
@vaijab From a Drone perspective it's an annoyance as the UI is misleading, but it's not a high priority.
However, I believe there is an audit requirement to know who pushed to prod. I may be wrong on that but you guys may know better than me. If we can't get that information then it's an issue if something goes wrong and we need to trace down who is accountable.

**Comment by vaijab** [comment]
@johnplacek we certainly need to fix this. I will see what I can do. Thanks.

**Comment by johnplacek** [comment]
Thanks. Would you like me to create a request on the backlog?

**Comment by johnplacek** [comment]
@vaijab ^^

**Comment by vaijab** [comment]
@johnplacek yeah, please.

**Comment by johnplacek** [comment]
@vaijab https://github.com/UKHomeOffice/central-devopsteam-board/issues/152 ... I may have just created a dup of this ticket. is there anywhere else I should be raising this?
